name: flutter_starter_kit
description: Jump-off_platform - A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Utilities from new structure
  get_it: ^7.6.4
  injectable: ^2.3.2
  flutter_bloc: ^8.1.3 # Using newer version
  equatable: ^2.0.5 # Using newer version
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # UI from new structure
  cupertino_icons: ^1.0.6
  go_router: ^12.1.1

  # Networking from new structure
  dio: ^5.3.3
  internet_connection_checker: ^1.0.0+1

  # Storage from new structure
  shared_preferences: ^2.2.2

  # Firebase (using newer versions from new pubspec)
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.1

  # Analytics (from new pubspec)
  firebase_analytics: ^10.7.1

  # Other utilities from new pubspec
  intl: ^0.18.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  uuid: ^4.2.1

  # Dependencies from old pubspec (to consider/keep)
  webview_flutter: ^3.0.0 # Kept from old
  fluttertoast: ^7.1.1 # Kept from old
  cached_network_image: ^3.2.0 # Kept from old

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dev dependencies from new structure
  build_runner: ^2.4.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.4
  mocktail: ^1.0.1

  # Dev dependencies from old pubspec (to consider/keep)
  flutter_native_splash: ^2.0.2 # Kept from old

# Kept from old pubspec if still needed
flutter_native_splash:
  image: assets/images/logo.png # This path needs to be valid in jump_off_platform
  color: "5E92F3"
  android_disable_fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 
    - assets/config/ 
